require("user.plugins")
require("user.lsp")
require("user.cmp")
require("user.fidget")
require("user.colorizer")
require("user.gui")
require("user.telescope")
require("user.dashboard")
-- require("user.colorscheme")
require("themes")
--require("user.indent")
require("user.nvimtree")
require("user.toggleterm")
require("user.comment")
require("user.snip")
require("user.keymaps")
require("user.options")
require("user.treesitter")
